{"name": "test_smena_pr", "status": "broken", "statusDetails": {"message": "ValueError: cannot convert float NaN to integer", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"11988787-d31d-436b-9ff0-d4b13322f428\")>, file_data = [{'balance': 2500, 'cycle': 'month', 'default': 'no', 'market': 'SCH', ...}]\napp_pages = <tests.conftest.app_pages.<locals>.Pages object at 0x000002876D6A8C20>\n\n    @allure.feature(\"Тестирование тарифа UP\")\n    def test_smena_pr(driver, file_data, app_pages):\n        \"\"\"\n        Запускает тесты на основе данных из файла.\n        \"\"\"\n        # for row in file_data:\n        #     execute_scenario(driver, row, app_pages)\n    \n        for row in file_data:\n>           process_tariff_changes(driver, row, app_pages)\n\ntest_app_android\\project\\tests\\test.py:316: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest_app_android\\project\\tests\\test.py:321: in process_tariff_changes\n    test_plan = TestChangePlan(row, app_pages)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <tests.test.TestChangePlan object at 0x000002876D6A8440>, data = {'balance': 2500, 'cycle': 'month', 'default': 'no', 'market': 'SCH', ...}\napp_pages = <tests.conftest.app_pages.<locals>.Pages object at 0x000002876D6A8C20>\n\n    def __init__(self, data, app_pages):\n    \n        self.data = data\n        self.app_pages = app_pages\n        #Переменные из файла\n        #Тариф\n        self.name_tp = str(data.get('new_tariff_name')) # Название тарифа\n>       self.value_gb = int(data.get('new_gb_value')) # Подключаемый пакет ГБ\nE       ValueError: cannot convert float NaN to integer\n\ntest_app_android\\project\\tests\\test.py:16: ValueError"}, "description": "\nЗапускает тесты на основе данных из файла.\n", "start": 1736861287200, "stop": 1736861287200, "uuid": "e4a23f04-9242-42e1-9b0c-29a3f1c1fe40", "historyId": "7e317dec957f8d84ca3cc6ce5c1ea4ff", "testCaseId": "7e317dec957f8d84ca3cc6ce5c1ea4ff", "fullName": "test_app_android.project.tests.test#test_smena_pr", "labels": [{"name": "feature", "value": "Тестирование тарифа UP"}, {"name": "parentSuite", "value": "test_app_android.project.tests"}, {"name": "suite", "value": "test"}, {"name": "host", "value": "DESKTOP-G72BB0H"}, {"name": "thread", "value": "7084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_app_android.project.tests.test"}]}